### ISSUE TITLE
Typed arrays and array buffer?

### ISSUE THREAD

**Issue by domenic** [traviskaufman/cycloneJS#24]
Any progress on supporting those?

**Comment by traviskaufman** [comment]
Hmm it doesn't look like they [mention](http://dev.w3.org/html5/spec-LC/common-dom-interfaces.html#safe-passing-of-structured-data) anything specific about typed arrays. 

That being said I don't think it would be all that difficult to implement as defined [here](https://www.khronos.org/registry/typedarray/specs/latest/#CLONING_AND_TRANSFERRING):

```javascript
'use strict';

var cy = require('cyclonejs');

cy.defineCloneProcedure({
  detect: detectBuffer,
  copy: cloneBuffer
});

cy.defineCloneProcedure({
  detect: detectTypedArray,
  copy: cloneTypedArray
});

function detectBuffer(obj) {
  return klass(obj) == 'ArrayBuffer';
}

function cloneBuffer(buf) {
  return copyBinData(new ArrayBuffer(buf.byteLength), buf);
}

function detectTypedArray(obj) {
  var klassRe = /^(?:Int8|Uint8|Uint8Clamped|Int16|Uint16|Int32|Uint32|Float23|Float64)Array$/;
  return klassRe.test(klass(obj));
}

function cloneTypedArray(typedArray) {
  var TypedArray = Object.getPrototypeOf(typedArray).constructor;
  var cloned = new TypedArray(
    cloneBuffer(typedArray.buffer),
    typedArray.byteOffset,
    typedArray.length
  );

  return copyBinData(cloned, typedArray);
}

function copyBinData(dst, src) {
  for (var i = 0, l = src.length; i < l; i++) {
    dst[i] = src[i];
  }

  return dst;
}

function klass(obj) {
  return Object.prototype.toString.call(obj).slice(8, -1);
}
```

Though I can see a case for it being included by default.

**Comment by domenic** [comment]
They're in the real HTML Standard: https://html.spec.whatwg.org/multipage/infrastructure.html#safe-passing-of-structured-data your link is to the outdated W3C fork

**Comment by traviskaufman** [comment]
awesome. Will implement and update.

**Comment by traviskaufman** [comment]
By the way, is there a place I can find unit/acceptance tests from W3C for the algorithm? Language doesn't matter just would like something to go off of :)

**Comment by domenic** [comment]
Probably these: https://github.com/w3c/web-platform-tests/blob/13bff083fba249ed260966bca65319b1b35d3f34/workers/semantics/structured-clone/worker-common.js

**Comment by traviskaufman** [comment]
@domenic PR is out as soon as TravisCI gives me green light I'll merge and release a new version.
