### ISSUE TITLE
Performance on small arrays of objects 

### ISSUE THREAD

**Issue by borntorun** [traviskaufman/cycloneJS#28]
Hi, I was searching an alternative for lodash clone and found cycloneJS which is a smaller and cleaner library for this operation. 
After some tests I found out that cycloneJS has not very good performance on small arrays of objects (small is <1000). But it performed very well on bigger arrays. (comparing with lodash clone) 
And bigger the array better is the performance of cyclone.js. 

I've put two tests in jsperf: 
http://jsperf.com/cyclonejs-vs-lodash-clone-on-small-array-of-objects
http://jsperf.com/cyclone-js-vs-lodash-clone-on-long-array-of-objects

Do you have any ideas why the slow numbers with small arrays?

**Comment by traviskaufman** [comment]
Thanks so much for taking the time to put those perf tests together and to let me know about this. I reckon the slower performance on small arrays has to do with the fact that I use `new Array(input.length)` rather than using the array literal syntax, which [seems to be a lot faster](http://stackoverflow.com/questions/7375120/why-is-arr-faster-than-arr-new-array). The idea behind using `new Array()` was to preserve the length of the original array even if it was sparse, but I think that's a tremendous edge case, and if switching to the literal syntax can lead to an order of magnitude increase in speed for smaller arrays, it's definitely worth investigating. I'm going to do some more research into this tonight.

**Comment by borntorun** [comment]
Thanks for the fast answer... I will wait for news.

**Comment by traviskaufman** [comment]
So unfortunately it looks like jsPerf is down :(

I created a branch that uses the array literal version, and compared it with the pre-existing version as well as with lodash.clonedeep, and ran perf tests using the [microbenchmark](https://www.npmjs.com/package/microbenchmark) module

```javascript
'use strict';

var microbenchmark = require('microbenchmark');
var clone = require('./cyclone').clone;
var oldClone = require('cycloneJS').clone;
var lodashClone = require('lodash.clonedeep');
var a = [1, 'two', true, {}, null];

console.log('Running 10000 iterations');
console.log();
printResults(microbenchmark.compare({
  'clone array using literal': function() {
    return clone(a);
  },

  'clone array w/ constructor': function() {
    return oldClone(a);
  },

  '_.clonedeep': function() {
    return lodashClone(a);
  }
}, 10000));

function printResults(results) {
  results.forEach(function(result) {
    console.log('-----------------------');
    console.log(result.name);
    console.log('-----------------------');
    console.log('Duration:', result.duration);
    if (result.relative) console.log('Relative:', result.relative);
    if (result.loss) console.log('Loss:', result.loss);
    console.log();
  });
}
```

Here is the result from one of the runs:

```
Running 10000 iterations

-----------------------
_.clonedeep
-----------------------
Duration: 1 cs 4 ms 135 μs 511 ns

-----------------------
clone array w/ constructor
-----------------------
Duration: 1 ds 9 cs 5 ms 886 μs 396 ns
Relative: + 1 ds 8 cs 1 ms 750 μs 885 ns
Loss: 1285.78%

-----------------------
clone array using literal
-----------------------
Duration: 2 ds 2 cs 3 ms 136 μs 607 ns
Relative: + 2 ds 9 ms 1 μs 96 ns
Loss: 1478.55%
```

So it does look like using the array literals speed things up quite a bit. I think I'm going to merge the change into the codebase. Thanks again for looking into this :)

**Comment by traviskaufman** [comment]
Reducing the number of iterations to just one, here are the results:

```
-----------------------
clone array w/ constructor
-----------------------
Duration: 373 μs 400 ns

-----------------------
_.clonedeep
-----------------------
Duration: 391 μs 439 ns
Relative: + 18 μs 39 ns
Loss: 4.83%

-----------------------
clone array using literal
-----------------------
Duration: 808 μs 942 ns
Relative: + 435 μs 542 ns
Loss: 116.64%
```
